### ISSUE TITLE
1.00 release does not contain a license

### ISSUE THREAD

**Issue by ppisar** [Perl5-Alien/dontpanic#2]
Releases linked from <https://perl5-alien.github.io/page/dontpanic.html> do not contain the LICENSE file and the license declaration as in README.md in this git repository.

This prevents from distributing the code by Fedora Linux distribution. Fedora needs to package the dontpanic library to be able to perform tests of Acme-Alien-DontPanic in restricted build environment that does have access to the Internet.

Please make a new dontpanic release that will contain the LICENSE and README.md files from this repository.

**Comment by plicease** [comment]
Okay, I think I have this right in version 1.01.  Please let me know if there is anything else missing.  Thank you for reporting this.
